# Generated by Django 4.2.2 on 2023-06-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
