# Generated by Django 4.2.2 on 2023-06-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_remove_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='identification',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
