# Generated by Django 4.2.2 on 2023-06-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
